#=========================================================================
# Simulation using Icarus Verilog
#=========================================================================
# Author : Kartik Prabhu
# Date   : May 13, 2021
#

name: open-icarus-simulation

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design.v
  - testbench.sv
  - design.sdf
  - design.args

outputs:
  - run.vcd

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - bash run.sh

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  testbench_name: tb
  dut_name: dut
  waveform: True
