#=========================================================================
# DRC using magic
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: open-magic-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds

outputs:
  - drc_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - cp inputs/adk/magicrc .magicrc
  - magic -noconsole -dnull run_drc.tcl | tee outputs/drc_results.log
  - grep "error" outputs/drc_results.log
